### ISSUE TITLE
don't work styles

### ISSUE THREAD

**Issue by pMonfared** [evandhq/react-persian-datepicker#37]
i use webpack 3.4.1 : (configuration file)

```
var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var pkg = require('./package.json');

// bundle dependencies in separate vendor bundle
var vendorPackages = Object.keys(pkg.dependencies).filter(function (el) {
    return el.indexOf('font') === -1; // exclude font packages from vendor bundle
});

/*
 * Default webpack configuration for development
 */
var config = {
    devtool: 'eval-source-map',
    cache: true,
    entry: {
        main: path.join(__dirname, "app", "App.js"),
        vendor: vendorPackages
    },
    output: {
        path: path.join(__dirname, "wwwroot", "js"),        //Note: For ASP.NET Core we need to put the output in wwwroot/js
        //in production mode make files have a .min.js ending - stops gulp's min:js concating them
        filename: process.env.NODE_ENV === 'production' ? '[name].min.js' : '[name].js',
        sourceMapFilename: '[file].map'
    },
    resolve: {
        extensions: ['.ts', '.js', '.json'],
        modules: [__dirname, 'node_modules']
    },
    plugins: [
        new webpack.LoaderOptionsPlugin({
            minimize: true,
            debug: true
        }),
        new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.js' }),
        new webpack.ProvidePlugin({ $: "jquery", jQuery: "jquery" })
    ],
    resolveLoader: {
        modules: ["node_modules"],
        extensions: [".js", ".json"],
        mainFields: ["loader", "main"]
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx|ts)$/,
                exclude: /node_modules/,/*(node_modules|bower_components)*/
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ["es2015", "react"]
                    }
                }
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,/*(node_modules|bower_components)*/
                use: [
                    'style-loader',
                    { loader: 'css-loader', options: { importLoaders: 1 } },
                    'autoprefixer-loader'
                ]
            },
            {
                test: /\.scss$/,
                exclude: /node_modules/,/*(node_modules|bower_components)*/
                use: [
                    'style-loader',
                    { loader: 'css-loader', options: { importLoaders: 1 } },
                    'autoprefixer-loader',
                    'sass-loader'
                ]
            },
            {
                test: /\.(png|jpg|ttf|eot)$/,
                /*exclude: /node_modules/,/*(node_modules|bower_components)*/
                use: {
                    loader: 'url-loader',
                    options: {
                        limit: 100000
                    }
                }
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                use: [
                    'file-loader'
                ]
            }
        ]
    }
}

/*
 * If bundling for production, optimize output
 */
if (process.env.NODE_ENV === 'production') {
    config.devtool = false;

    config.plugins = [
        //new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            beautify: false,
            mangle: {
                screw_ie8: true,
                keep_fnames: true
            },
            comments: false,
            compress: { warnings: false, screw_ie8: true }
        }),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify('production')
        })
    ];
}

module.exports = config;

```

when i run cmd : dev-watch 
webpack getback this error : 

```
ERROR in ./node_modules/react-persian-datepicker/lib/styles/basic.css
Module parse failed: H:\GitLab\src\Sample\node_modules\react-persian-datepicker\lib\styles\basic.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .calendarContainer {
|   border-radius: 3px;
|   box-shadow: 0 3px 10px #dbdbdb;
 @ ./node_modules/react-persian-datepicker/lib/components/Calendar.js 255:10-40
 @ ./node_modules/react-persian-datepicker/lib/index.js
```

i changed webpack config loaders ( css ) to this codes :

```
test: /\.css$/,
                use: [
                    'style-loader',
                    { loader: 'css-loader', options: { importLoaders: 1 } },
                    'autoprefixer-loader'
                ]
```

and webpack complie without any error
but don't show style for datepicker like this photo:

![image](https://user-images.githubusercontent.com/10448255/29777538-ab1c5628-8c21-11e7-9d83-4e03ad2b9d35.png)

**Comment by maryam-mokhtari** [comment]
same problem

**Comment by mohebifar** [comment]
Can you please try logging `require('react-persian-datepicker\lib\styles\basic.css')`?

```js
console.log(require('react-persian-datepicker\lib\styles\basic.css'));
```

**Comment by htondkar** [comment]
there is an alternative with working css: 
https://www.npmjs.com/package/react-persian-calendar

**Comment by fahamidev** [comment]
@mohebifar 

Hi .
i use "webpack": "^2.7.0"
and i do this :
`import basic from 'react-persian-datepicker/lib/styles/basic.css';`

 then inside the constructor :
```
constructor(props) {
        super(props);
        console.log(basic);
}
```

And finally the result of the console is empty Object : {}

And in my webpack.config is like this :
```
{
                test: /\.css$/,
                include: /node_modules/,
                use: [
                    'style-loader',
                    'css-loader'
                ]
            },
            {
                test: /\.s[ac]ss$/,
                exclude: /node_modules/,
                use: ['style-loader',
                    {
                        loader: 'css-loader',
                        options: {sourceMap: true}
                    },
                    'sass-loader'
                ]
            }
```
thanks for your help

**Comment by mohebifar** [comment]
@htondkar @pMonfared @mayyamak You _must_ set the `modules` option of `css-loader` to `true`:
```
{ loader: 'css-loader', options: {modules: true, sourceMap: true} }
```

**Comment by fahamidev** [comment]
@mohebifar  thanks for your help . I set up the ( options ) and it works right now.

But there is another problem . When click on day, the (div.tether-element)class does not close .
What is your idea for this problem.solution ?

**Comment by EhsanFahami** [comment]
Hi.
I'm having trouble reusing the package and i can't use from datepicker now.
I have this error :
```
projectName/node_modules/react-persian-datepicker/lib/styles/basic.css:1
(function (exports, require, module, __filename, __dirname) { .calendarContainer {
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.defineProperty.value (projectName/build/bundle.js:1018:18)

```

> package.json
```
"devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-latest": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "css-loader": "^0.28.9",
    "node-sass": "^4.7.2",
    "npm-run-all": "^4.1.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "uglifyjs-webpack-plugin": "^1.2.0",
    "webpack": "^3.11.0",
    "webpack-node-externals": "^1.6.0"
  }
```
This project has three webpack files : webpack.server.js & webpack.client.js & webpack.base.js . The webpack.base.js file is used among them as a shared file.
The settings inside the webpack.base.js file are as follows :

> webpack.base.js
```
module.exports = {
    module : {
        rules : [
            {
                test    : /\.js?$/,
                loader  : "babel-loader",
                exclude : /node-modules/,
                options : {
                    presets : [
                        ["es2015", {"modules": false}],
                        'react',
                        'stage-0',
                        'stage-2',
                        ["env", {
                            targets : {browsers : ['last 2 versions ']}
                        }]
                    ]
                }
            },
            {
                test: /\.css$/,
                include: /node_modules/,
                use: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: { modules: true, sourceMap: true }
                    }
                ]
            }
        ]
    }
};
```
**I set the modules option of css-loader to true** , but the settings have not been applied or I have not reached the result through this way;

Thanks for the help you will get.

**Comment by soroushoracle** [comment]
Use this css file. @thg303 gathered it from the one in the repository. don't forget to fix the extension to ".css"
[evan-calender-style.css.txt](https://github.com/evandhq/react-persian-datepicker/files/785143/evan-calender-style.css.txt)

After adding styles, you need to present the styles to the **DatePicker** :

>  const styles= {
       calendarContainer: 'calendarContainer',
       dayPickerContainer: 'dayPickerContainer',
       monthsList: 'monthsList',
       daysOfWeek: 'daysOfWeek',
       dayWrapper: 'dayWrapper',
       selected: 'selected',
       heading: 'heading'
}

then: 
     
` <DatePicker calendarStyles={styles}/>`

**Comment by FareheSoheil** [comment]
@mohebifar  hi

**Comment by FareheSoheil** [comment]
@mohebifar Hi 
sorry but when I set this : 
{ loader: 'css-loader', options: {modules: true, sourceMap: true} }
my css modules don't work 
can you help me through this? `{
                test: /\.css$/,
                use: [
                    require.resolve('style-loader'),
                    {
                        loader: require.resolve('css-loader'),
                        options: {
                            importLoaders: 1,
                            modules: true
                        }
                    },`

**Comment by FareheSoheil** [comment]
@mohebifar  tnx this was a great help :)

**Comment by FareheSoheil** [comment]
@mohebifar is there anyway to include the styles without setting 'modules' to true?
because it messes up some other styles on my app :(

**Comment by asiye** [comment]
> const styles = {
> calendarContainer: "calendarContainer",
> dayPickerContainer: "dayPickerContainer",
> monthsList: "monthsList",
> daysOfWeek: "daysOfWeek",
> dayWrapper: "dayWrapper",
> selected: "selected",
> heading: "heading",
> next: "next",
> prev: "prev",
> title: "title",
> }

```
<Calendar styles={ styles } />
<DatePicker calendarStyles={ styles } />
```

**Comment by mohebifar** [comment]
@FareheSoheil What @asiye suggested is exactly what you would have to do if you don't want to use `css-modules`.

**Comment by FareheSoheil** [comment]
@asiye @mohebifar   I did what you told , but still styles are not applied , although there are no undefined classes. Don't know what is happening :(
![screenshot 44](https://user-images.githubusercontent.com/18319125/47824893-43efa300-dd84-11e8-8f72-b0f19a07e272.png)
